version: '3.3'

services:
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  db:
    image: postgres
    volumes:
      - postgres_data2:/var/lib/postgresql/data/
    env_file:
      - .env

  web:
    build: blog
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - db
    env_file:
      - .env
    command:  python manage.py migrate && python manage.py generate_posts 
  worker:
    restart: always
    build: blog
    depends_on:
      - redis
      - web
      - nginx
    command: 'celery -A blog worker -l info'

  beat:
    restart: always
    build: blog
    depends_on:
      - redis
      - web
    command: 'celery -A blog beat -l info'

  nginx:
    build: infra
    ports:
      - "8080:8080"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
      # - static_volume:/static/
      # - static_media:/app/media
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
  postgres_data2:
